test_that("engine_health returns sane basic checks", {
  eng <- engine_create(demo_domains(), seed = 1)
  eng <- simulate_engine(eng, chooser = function(q) "A")
  eng <- engine_compute(eng)

  h <- engine_health(eng)
  expect_s3_class(h, "paprika_health")

  expect_true(is.numeric(h$n_decisions))
  expect_equal(h$n_equal, 0)
  expect_equal(h$n_strict, h$n_decisions)

  # All questions generated by the engine should be 2-diff tradeoffs
  expect_equal(h$pct_two_diff, 100)

  # With 5 criteria, after enough questions we should have seen all pairs
  expect_true(isTRUE(h$pairs_covered))

  # Solver status should be 0 when computed successfully
  expect_equal(h$solve_status, 0)
})
